# cloudbuild.yaml for MLOps pipeline

options:
  # Store logs in Cloud Logging and also GCS bucket
  logging: CLOUD_LOGGING_ONLY
  # Uncomment and set if you want logs in a bucket as well
  # logsBucket: gs://mlops-build-logs

# Specify the service account
serviceAccount: pro-vigil-mlops@pro-vigil-dev.iam.gserviceaccount.com

steps:
  # -------------------------
  # Build Docker images
  # -------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-data-fetcher:v1.0.6', './components/data_fetching']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-data-preprocessor:v1.0.7', './components/preprocessing']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-feature-engineer:v1.0.3', './components/feature_engineering']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-data-splitter:v1.0.0', './components/data_splitting']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-multi-model-trainer:v2.0.0', './components/training']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-model-evaluator:v1.0.0', './components/evaluation']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-model-registry:v2.0.5', './components/model_registry']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-email-notification:v1.0.0', './components/email_notification']

  # -------------------------
  # Push Docker images
  # -------------------------
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-data-fetcher:v1.0.6']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-data-preprocessor:v1.0.7']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-feature-engineer:v1.0.3']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-data-splitter:v1.0.0']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-multi-model-trainer:v2.0.0']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-model-evaluator:v1.0.0']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-model-registry:v2.0.5']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-email-notification:v1.0.0']

  # -------------------------
  # Install gcloud and publish Pub/Sub notification
  # -------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "📦 Sending Pub/Sub notification..."
        gcloud pubsub topics publish cloud-build-done \
          --message '{"status": "SUCCESS", "trigger": "docker-build-trigger"}'
        echo "✅ Pub/Sub notification sent successfully."

# -------------------------
# List of images built
# -------------------------
images:
  - 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-data-fetcher:v1.0.6'
  - 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-data-preprocessor:v1.0.7'
  - 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-feature-engineer:v1.0.3'
  - 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-data-splitter:v1.0.0'
  - 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-multi-model-trainer:v2.0.0'
  - 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-model-evaluator:v1.0.0'
  - 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-model-registry:v2.0.5'
  - 'us-central1-docker.pkg.dev/pro-vigil-dev/mlops/mlops-email-notification:v1.0.0'
